[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "fh-echarts"
dynamic = ["version"]
description = ""
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
authors = [{name = "markkvdb", email = "github@mvanderbroek.com"}]
keywords = ['nbdev']
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "python-fasthtml",
]

[project.urls]
Repository = "https://github.com/markkvdb/fh-echarts"
Documentation = "https://markkvdb.github.io/fh-echarts/"

[project.entry-points.nbdev]
fh_echarts = "fh_echarts._modidx:d"

[project.optional-dependencies]
dev = [
    "pandas>=2.3.3",
]

[tool.setuptools.dynamic]
version = {attr = "fh_echarts.__version__"}

[tool.setuptools.packages.find]
include = ["fh_echarts"]

[tool.nbdev]
