# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fh-echarts',
                'doc_host': 'https://markkvdb.github.io',
                'git_url': 'https://github.com/markkvdb/fh-echarts',
                'lib_path': 'fh_echarts'},
  'syms': { 'fh_echarts.core': { 'fh_echarts.core.EChart': ('core.html#echart', 'fh_echarts/core.py'),
                                 'fh_echarts.core.EChartJS': ('core.html#echartjs', 'fh_echarts/core.py'),
                                 'fh_echarts.core.EChartOOB': ('core.html#echartoob', 'fh_echarts/core.py'),
                                 'fh_echarts.core.EChartUpdate': ('core.html#echartupdate', 'fh_echarts/core.py'),
                                 'fh_echarts.core.EChartsEncoder': ('core.html#echartsencoder', 'fh_echarts/core.py'),
                                 'fh_echarts.core.EChartsEncoder._convert': ('core.html#echartsencoder._convert', 'fh_echarts/core.py'),
                                 'fh_echarts.core.EChartsEncoder.encode': ('core.html#echartsencoder.encode', 'fh_echarts/core.py'),
                                 'fh_echarts.core.JSFunc': ('core.html#jsfunc', 'fh_echarts/core.py'),
                                 'fh_echarts.core.echarts_header': ('core.html#echarts_header', 'fh_echarts/core.py'),
                                 'fh_echarts.core.preview_echart': ('core.html#preview_echart', 'fh_echarts/core.py')}}}
